# 데이터 로드 

In [1]:
import pandas as pd
import numpy as np
import chardet

# encoding 설정
with open('modeldata_df.csv', 'rb') as file:
    result = chardet.detect(file.read())
    encoding = result['encoding'] # 'utf-8'

In [2]:
# 데이터프레임 출력 옵션 
# row 생략 없이 출력
# pd.set_option('display.max_rows', None)
# col 생략 없이 출력
pd.set_option('display.max_columns', None)

In [3]:
model_df = pd.read_csv('modeldata_df_NAdropped.csv', encoding=encoding)

In [4]:
model_df

Unnamed: 0          tm  ta_max_t-0  ta_min_t-0  ta_max_min_t-0  \
0                0  2018-01-03        -0.4        -7.1             6.7   
1                1  2018-01-04        -0.7        -8.7             8.0   
2                2  2018-01-04        -0.7        -8.7             8.0   
3                3  2018-01-05         1.6        -5.6             7.2   
4                4  2018-01-05         1.6        -5.6             7.2   
...            ...         ...         ...         ...             ...   
544395      597663  2023-12-27         6.6        -3.0             9.6   
544396      597664  2023-12-28         7.4        -3.8            11.2   
544397      597665  2023-12-29         9.3         1.6             7.7   
544398      597666  2023-12-30         6.0         1.4             4.6   
544399      597667  2023-12-31         3.0         0.6             2.4   

        rn_day_t-0  ws_max_t-0  ws_ins_max_t-0  ws_mean_t-0  ws_min_t-0  \
0              0.0         3.5             6.6          2.1         0.8   
1              0.0         3.5             5.8          1.4         0.5   
2              0.0         3.5             5.8          1.4         0.5   
3              0.0         3.6             8.0          1.7         0.6   
4              0.0         3.6             8.0          1.7         0.6   
...            ...         ...             ...          ...         ...   
544395         0.0         4.1             5.5          2.2         0.7   
544396         0.0         6.5            10.1          3.0         0.2   
544397         0.0         7.2            10.2          4.1         1.9   
544398         0.5         5.8             9.0          1.9         0.3   
544399        11.0         5.2             7.9          2.0         0.2   

        hm_max_t-0  hm_mean_t-0  hm_min_t-0  ta_max_t-1  ta_min_t-1  \
0             54.0         41.1        29.3         1.8        -4.3   
1             56.7         44.1        31.3        -0.4        -7.1   
2             56.7         44.1        31.3        -0.4        -7.1   
3             56.0         48.5        33.5        -0.7        -8.7   
4             56.0         48.5        33.5        -0.7        -8.7   
...            ...          ...         ...         ...         ...   
544395        83.6         61.7        48.1         6.5         0.1   
544396        89.0         54.1        24.5         6.6        -3.0   
544397        54.5         44.2        29.8         7.4        -3.8   
544398        94.4         68.9        46.0         9.3         1.6   
544399        95.9         91.9        85.6         6.0         1.4   

        ta_max_min_t-1  rn_day_t-1  ws_max_t-1  ws_ins_max_t-1  ws_mean_t-1  \
0                  6.1         0.0         4.9             8.5          1.8   
1                  6.7         0.0         3.5             6.6          2.1   
2                  6.7         0.0         3.5             6.6          2.1   
3                  8.0         0.0         3.5             5.8          1.4   
4                  8.0         0.0         3.5             5.8          1.4   
...                ...         ...         ...             ...          ...   
544395             6.4         0.0        10.5            15.5          5.9   
544396             9.6         0.0         4.1             5.5          2.2   
544397            11.2         0.0         6.5            10.1          3.0   
544398             7.7         0.0         7.2            10.2          4.1   
544399             4.6         0.5         5.8             9.0          1.9   

        ws_min_t-1  hm_max_t-1  hm_mean_t-1  hm_min_t-1  ta_max_t-2  \
0              0.2        70.6         43.6        20.1         3.8   
1              0.8        54.0         41.1        29.3         1.8   
2              0.8        54.0         41.1        29.3         1.8   
3              0.5        56.7         44.1        31.3        -0.4   
4              0.5        56.7         44.1        31.3      

# 전처리 (scaling)

In [20]:
# Robust Scaling
from sklearn.preprocessing import RobustScaler

scaled_df = model_df.copy()

# scaling 할 컬럼 리스트
scale_list = ['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']

for c in scale_list:
    transformer = RobustScaler()
    scaled_df[c] = transformer.fit_transform(scaled_df[[c]])

In [21]:
scaled_df

Unnamed: 0          tm  ta_max_t-0  ta_min_t-0  ta_max_min_t-0  \
0                0  2018-01-03   -1.303797   -0.855556       -0.625000   
1                1  2018-01-04   -1.322785   -0.944444       -0.392857   
2                2  2018-01-04   -1.322785   -0.944444       -0.392857   
3                3  2018-01-05   -1.177215   -0.772222       -0.535714   
4                4  2018-01-05   -1.177215   -0.772222       -0.535714   
...            ...         ...         ...         ...             ...   
544395      597663  2023-12-27   -0.860759   -0.627778       -0.107143   
544396      597664  2023-12-28   -0.810127   -0.672222        0.178571   
544397      597665  2023-12-29   -0.689873   -0.372222       -0.446429   
544398      597666  2023-12-30   -0.898734   -0.383333       -1.000000   
544399      597667  2023-12-31   -1.088608   -0.427778       -1.392857   

        rn_day_t-0  ws_max_t-0  ws_ins_max_t-0  ws_mean_t-0  ws_min_t-0  \
0              0.0   -0.190476       -0.117647     0.545455        1.75   
1              0.0   -0.190476       -0.352941    -0.090909        1.00   
2              0.0   -0.190476       -0.352941    -0.090909        1.00   
3              0.0   -0.142857        0.294118     0.181818        1.25   
4              0.0   -0.142857        0.294118     0.181818        1.25   
...            ...         ...             ...          ...         ...   
544395         0.0    0.095238       -0.441176     0.636364        1.50   
544396         0.0    1.238095        0.911765     1.363636        0.25   
544397         0.0    1.571429        0.941176     2.363636        4.50   
544398         0.5    0.904762        0.588235     0.363636        0.50   
544399        11.0    0.619048        0.264706     0.454545        0.25   

        hm_max_t-0  hm_mean_t-0  hm_min_t-0  ta_max_t-1  ta_min_t-1  \
0        -2.223529    -1.199859   -0.525180   -1.150943   -0.700000   
1        -2.064706    -1.072740   -0.453237   -1.289308   -0.855556   
2        -2.064706    -1.072740   -0.453237   -1.289308   -0.855556   
3        -2.105882    -0.886299   -0.374101   -1.308176   -0.944444   
4        -2.105882    -0.886299   -0.374101   -1.308176   -0.944444   
...            ...          ...         ...         ...         ...   
544395   -0.482353    -0.326977    0.151079   -0.855346   -0.455556   
544396   -0.164706    -0.649011   -0.697842   -0.849057   -0.627778   
544397   -2.194118    -1.068503   -0.507194   -0.798742   -0.672222   
544398    0.152941    -0.021893    0.075540   -0.679245   -0.372222   
544399    0.241176     0.952684    1.500000   -0.886792   -0.383333   

        ta_max_min_t-1  rn_day_t-1  ws_max_t-1  ws_ins_max_t-1  ws_mean_t-1  \
0            -0.732143         0.0    0.476190        0.441176     0.272727   
1            -0.625000         0.0   -0.190476       -0.117647     0.545455   
2            -0.625000         0.0   -0.190476       -0.117647     0.545455   
3            -0.392857         0.0   -0.190476       -0.352941    -0.090909   
4            -0.392857         0.0   -0.190476       -0.352941    -0.090909   
...                ...         ...         ...             ...          ...   
544395       -0.678571         0.0    3.142857        2.500000     4.000000   
544396       -0.107143         0.0    0.095238       -0.441176     0.636364   
544397        0.178571         0.0    1.238095        0.911765     1.363636   
544398       -0.446429         0.0    1.571429        0.941176     2.363636   
544399       -1.000000         0.5    0.904762        0.588235     0.363636   

        ws_min_t-1  hm_max_t-1  hm_mean_t-1  hm_min_t-1  ta_max_t-2  \
0             0.25   -1.254438    -1.106838   -0.862816   -1.025157   
1             1.75   -2.236686    -1.213675   -0.530686   -1.150943   
2             1.75   -2.236686    -1.213675   -0.530686   -1.150943   
3             1.00   -2.076923    -1.085470   -0.458484   -1.289308   
4             1.00   -2.076923    -1.085470   -0.458484   -1.

# 의사결정트리
- 알고리즘
    - C4.5: 엔트로피 계수를 가장 많이 감소시키는 변수를 찾아 분리
    - CART (Classification And Regression Tree): 범주형 목표변수인 경우 지니지수를 가장 많이 감소시키는 변수로 분리
    - CHAID (Chi-Squeared Automatic Interaction Detection): p-value가 가장 작은 변수를 찾아 분리
 
- recall, precision 파라미터
    - macro: 각 클래스에 동일한 중요도 부여, 클래스 불균형 무시
    - micro: 전체 클래스의 총 합계를 사용하여 계산, 클래스의 불균형 반영
    - weighted: 각 클래스의 샘플 수를 가중치로 사용하여 계산, 클래스의 불균형 반영 

In [5]:
### isFire 제외 화재 발생데이터만 참고! ###

# nan 값 전처리 - y 값
# df['type'] = df['type'].fillna('없음')
# df['ignition'] = df['ignition'].fillna('없음')
# df['location'] = df['location'].fillna('없음')
# df['grade'] = df['grade'].fillna('없음')

# df['casualties'] = df['casualties'].fillna(-1)
# df['property_damage'] = df['property_damage'].fillna(-1)

In [6]:
# drop na - x 값 => 전처리로 해결!
# df = df.dropna()

In [7]:
model_df.isna().sum()

Unnamed: 0              0
tm                      0
ta_max_t-0              0
ta_min_t-0              0
ta_max_min_t-0          0
rn_day_t-0              0
ws_max_t-0              0
ws_ins_max_t-0          0
ws_mean_t-0             0
ws_min_t-0              0
hm_max_t-0              0
hm_mean_t-0             0
hm_min_t-0              0
ta_max_t-1              0
ta_min_t-1              0
ta_max_min_t-1          0
rn_day_t-1              0
ws_max_t-1              0
ws_ins_max_t-1          0
ws_mean_t-1             0
ws_min_t-1              0
hm_max_t-1              0
hm_mean_t-1             0
hm_min_t-1              0
ta_max_t-2              0
ta_min_t-2              0
ta_max_min_t-2          0
rn_day_t-2              0
ws_max_t-2              0
ws_ins_max_t-2          0
ws_mean_t-2             0
ws_min_t-2              0
hm_max_t-2              0
hm_mean_t-2             0
hm_min_t-2              0
type               335537
ignition           335537
location           335537
grade       

## x: 기상데이터

### 1) 화재 type ~ 기상데이터

In [22]:
# 화재 미발생 데이터 제외
df = scaled_df.dropna()

In [23]:
from sklearn.metrics import recall_score, make_scorer

# 다지분류용 recall 스코어러 정의
scorer = make_scorer(recall_score, average='macro')

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix
import warnings 
warnings.filterwarnings('ignore')

# x값, y값 분리
x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# DecisionTree Classifier 생성 
model = DecisionTreeClassifier(random_state=42)

# StratifiedKFold 
skfold = StratifiedKFold(n_splits=3)
k=0 # 교차검증 횟수
cv_acc = [] # 교차검증마다 정확도 저장 

for train_idx, test_idx in skfold.split(x, y):
    k += 1
    print(f'{k}번째 검증 데이터 셋')

    x_train, x_test = x.iloc[train_idx], x.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(x_train, y_train)
    y_hat = model.predict(x_test)
    # 평가지표 
    accuracy = accuracy_score(y_test, y_hat)
    precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
    recall = recall_score(y_test, y_hat, average='macro')
    cm = confusion_matrix(y_test, y_hat)
    
    print(f'정확도: {accuracy:.2f}')
    print(f'정밀도: {precision:.2f}')
    print(f'재현율: {recall:.2f}')
    print(cm)
    print()
    cv_acc.append(accuracy)

print()
print(f'평균 정확도: {np.mean(cv_acc):.2f}')

1번째 검증 데이터 셋
정확도: 0.49
정밀도: 0.17
재현율: 0.17
[[31323  7129   189    35  1559  4441]
 [ 9207  2075    63     5   474  1122]
 [  167    32     2     0     3    29]
 [   40     6     0     0     2     8]
 [ 2345   556     1     3   146   255]
 [ 6246  1158    36     4   256   704]]

2번째 검증 데이터 셋
정확도: 0.42
정밀도: 0.16
재현율: 0.16
[[26126  7867   112    24  3539  7008]
 [ 8370  1912    32     8  1116  1507]
 [  151    42     1     2     5    32]
 [   33     8     0     0     5    10]
 [ 2117   592    11     3   258   326]
 [ 5505  1226    27     3   623  1020]]

3번째 검증 데이터 셋
정확도: 0.42
정밀도: 0.16
재현율: 0.16
[[25408 10269   351    35  3268  5345]
 [ 7773  2638    78     6  1185  1265]
 [  156    39     0     0    18    20]
 [   33     9     5     0     5     5]
 [ 1911   726    17     0   328   324]
 [ 5140  1656    67     7   634   900]]


평균 정확도: 0.44


In [25]:
# GridSearchCV: scoring=accuracy

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_type1 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_type1, param_grid=param_grid, cv=cv, scoring='accuracy', n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 10, 'min_samples_split': 2}
Best cross-validation accuracy: 0.64
정확도: 0.64
정밀도: 0.21
재현율: 0.17
[[19929   103     0     0    18    55]
 [ 5747    55     0     0     9    14]
 [  104     1     0     0     0     0]
 [   25     0     0     0     0     0]
 [ 1459    18     0     0     9     2]
 [ 3754    19     0     0     2     7]]

Classification Report:
              precision    recall  f1-score   support

       유형_건축       0.64      0.99      0.78     20105
       유형_기타       0.28      0.01      0.02      5825
       유형_선박       0.00      0.00      0.00       105
      유형_위험물       0.00      0.00      0.00        25
       유형_임야       0.24      0.01      0.01      1488
      유형_자동차       0.09      0.00      0.00      3782

    accuracy                           0.64     31330
   macro avg       0.21      0.17      0.14     31330
weighted avg       0.49      0.64      0.50     31330



#### Parameter Tuning (1)

In [26]:
# 1

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, recall_score, make_scorer
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_type1 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_type1, param_grid=param_grid, cv=cv, scoring=scorer, n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'entropy', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best cross-validation accuracy: 0.19
정확도: 0.52
정밀도: 0.20
재현율: 0.20
[[14584  2950    54    16   659  1842]
 [ 3845  1197    20     7   276   480]
 [   66    23     3     0     4     9]
 [   18     3     0     0     1     3]
 [  890   282     6     2   195   113]
 [ 2684   592     6     3   108   389]]

Classification Report:
              precision    recall  f1-score   support

       유형_건축       0.66      0.73      0.69     20105
       유형_기타       0.24      0.21      0.22      5825
       유형_선박       0.03      0.03      0.03       105
      유형_위험물       0.00      0.00      0.00        25
       유형_임야       0.16      0.13      0.14      1488
      유형_자동차       0.14      0.10      0.12      3782

    accuracy                           0.52     31330
   macro avg       0.20      0.20      0.20     31330
weighted avg       0.49      0.52      0.51     31330



#### Parameter Tuning (2)

In [27]:
# 2

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, recall_score, make_scorer
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_type2 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 3, 5, 10],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [10, 20, 30]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_type2, param_grid=param_grid, cv=cv, scoring=scorer, n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 10, 'min_samples_split': 2}
Best cross-validation accuracy: 0.18
정확도: 0.55
정밀도: 0.19
재현율: 0.18
[[15690  2877     0     0   295  1243]
 [ 4222  1121     0     0   125   357]
 [   80    16     0     0     1     8]
 [   21     3     0     0     0     1]
 [  983   324     0     0    88    93]
 [ 2955   526     0     0    52   249]]

Classification Report:
              precision    recall  f1-score   support

       유형_건축       0.66      0.78      0.71     20105
       유형_기타       0.23      0.19      0.21      5825
       유형_선박       0.00      0.00      0.00       105
      유형_위험물       0.00      0.00      0.00        25
       유형_임야       0.16      0.06      0.09      1488
      유형_자동차       0.13      0.07      0.09      3782

    accuracy                           0.55     31330
   macro avg       0.19      0.18      0.18     31330
weighted avg       0.49      0.55      0.51     31330



#### Parameter Tuning (3)

In [28]:
# 3

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, recall_score, make_scorer
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_type3 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 3, 5],
    'min_samples_split': [2, 3, 5],
    'min_samples_leaf': [1, 3, 5, 10]
}


# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_type3, param_grid=param_grid, cv=cv, scoring=scorer, n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'entropy', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5}
Best cross-validation accuracy: 0.19
정확도: 0.52
정밀도: 0.20
재현율: 0.19
[[14422  3043    39    13   688  1900]
 [ 3840  1165    20     2   289   509]
 [   68    22     0     0     5    10]
 [   17     4     0     0     1     3]
 [  879   289     4     0   197   119]
 [ 2636   613     9     3   120   401]]

Classification Report:
              precision    recall  f1-score   support

       유형_건축       0.66      0.72      0.69     20105
       유형_기타       0.23      0.20      0.21      5825
       유형_선박       0.00      0.00      0.00       105
      유형_위험물       0.00      0.00      0.00        25
       유형_임야       0.15      0.13      0.14      1488
      유형_자동차       0.14      0.11      0.12      3782

    accuracy                           0.52     31330
   macro avg       0.20      0.19      0.19     31330
weighted avg       0.49      0.52      0.50     31330



### 2) ignition ~ 기상데이터

In [33]:
# 화재 미발생 데이터 제외
df = scaled_df.dropna()

In [34]:
# 다지분류용 scorer 정의
from sklearn.metrics import recall_score, make_scorer
scorer = make_scorer(recall_score, average='macro')

#### Parameter Tuning (1)

In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['ignition']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_ignition1 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_ignition1, param_grid=param_grid, cv=cv, scoring=scorer, n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'entropy', 'max_depth': 50, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best cross-validation accuracy: 0.14
정확도: 0.35
정밀도: 0.14
재현율: 0.14
[[   0    4   16   11    1   57    0   31    2]
 [   2    7   48   58    7  145    3   84    6]
 [  21   43  485  431   45 1438   25  713   44]
 [  19   46  495  563   40 1738   21  696   43]
 [   2    5   29   36    8  143    1   59    5]
 [  92  206 1830 1976  154 8048   55 2648  167]
 [   0    5   20   27    4   57   17   64    3]
 [  40  124 1015 1028   80 3451   58 1841  108]
 [   5    7   67   72   10  252    2  107   14]]

Classification Report:
              precision    recall  f1-score   support

       발화_가스       0.00      0.00      0.00       122
       발화_교통       0.02      0.02      0.02       360
       발화_기계       0.12      0.15      0.13      3245
       발화_기타       0.13      0.15      0.14      3661
       발화_방화       0.02      0.03      0.03       288
      발화_부주의       0.53      0.53     

#### Parameter Tuning (2)

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['ignition']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_ignition2 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_ignition2, param_grid=param_grid, cv=cv, scoring=scorer, n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'entropy', 'max_depth': 50, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best cross-validation accuracy: 0.14
정확도: 0.35
정밀도: 0.14
재현율: 0.14
[[   0    4   16   11    1   57    0   31    2]
 [   2    7   48   58    7  145    3   84    6]
 [  21   43  485  431   45 1438   25  713   44]
 [  19   46  495  563   40 1738   21  696   43]
 [   2    5   29   36    8  143    1   59    5]
 [  92  206 1830 1976  154 8048   55 2648  167]
 [   0    5   20   27    4   57   17   64    3]
 [  40  124 1015 1028   80 3451   58 1841  108]
 [   5    7   67   72   10  252    2  107   14]]

Classification Report:
              precision    recall  f1-score   support

       발화_가스       0.00      0.00      0.00       122
       발화_교통       0.02      0.02      0.02       360
       발화_기계       0.12      0.15      0.13      3245
       발화_기타       0.13      0.15      0.14      3661
       발화_방화       0.02      0.03      0.03       288
      발화_부주의       0.53      0.53     

### 3) location ~ 기상데이터

In [37]:
# 화재 미발생 데이터 제외
df = scaled_df.dropna()

In [38]:
# 다지분류용 scorer 정의
from sklearn.metrics import recall_score, make_scorer
scorer = make_scorer(recall_score, average='macro')

#### Parameter Tuning (1)

In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['location']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_location1 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_location1, param_grid=param_grid, cv=cv, scoring=scorer, n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 10, 'min_samples_split': 2}
Best cross-validation accuracy: 0.20
정확도: 0.30
정밀도: 0.20
재현율: 0.20
[[  44    2   78 1325 2534  118]
 [  19    0   43  600  831   33]
 [  44    2  112 1514 2438  147]
 [  71    3  113 3624 3352  150]
 [  62    5  166 2456 5461  311]
 [  54    0   81 1614 3678  245]]

Classification Report:
              precision    recall  f1-score   support

       장소_교통       0.15      0.01      0.02      4101
       장소_기타       0.00      0.00      0.00      1526
       장소_산업       0.19      0.03      0.05      4257
       장소_야외       0.33      0.50      0.39      7313
       장소_주거       0.30      0.65      0.41      8461
       장소_집객       0.24      0.04      0.07      5672

    accuracy                           0.30     31330
   macro avg       0.20      0.20      0.16     31330
weighted avg       0.25      0.30      0.22     31330



### 4) grade ~ 기상데이터

In [40]:
# 화재 미발생 데이터 제외
df = scaled_df.dropna()

In [41]:
# 다지분류용 scorer 정의
from sklearn.metrics import recall_score, make_scorer
scorer = make_scorer(recall_score, average='macro')

#### Paramter Tuning (1)

In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['ignition']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_grade1 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_grade1, param_grid=param_grid, cv=cv, scoring=scorer, n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

Best parameters found:  {'criterion': 'entropy', 'max_depth': 50, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best cross-validation accuracy: 0.14
정확도: 0.35
정밀도: 0.14
재현율: 0.14
[[   0    4   16   11    1   57    0   31    2]
 [   2    7   48   58    7  145    3   84    6]
 [  21   43  485  431   45 1438   25  713   44]
 [  19   46  495  563   40 1738   21  696   43]
 [   2    5   29   36    8  143    1   59    5]
 [  92  206 1830 1976  154 8048   55 2648  167]
 [   0    5   20   27    4   57   17   64    3]
 [  40  124 1015 1028   80 3451   58 1841  108]
 [   5    7   67   72   10  252    2  107   14]]

Classification Report:
              precision    recall  f1-score   support

       발화_가스       0.00      0.00      0.00       122
       발화_교통       0.02      0.02      0.02       360
       발화_기계       0.12      0.15      0.13      3245
       발화_기타       0.13      0.15      0.14      3661
       발화_방화       0.02      0.03      0.03       288
      발화_부주의       0.53      0.53     

### 5) isFire ~ 기상데이터
- 이진분류
- threshold 조정: 0.25, 0.5 (default), 0.75

In [43]:
# 화재 미발생 데이터 포함
df = scaled_df

## x: 기상 + 기상특보

## x: 기상 + 기상측보 + 지역데이터