# 데이터 로드 

In [1]:
import pandas as pd
import numpy as np
import chardet

# encoding 설정
with open('modeldata_df.csv', 'rb') as file:
    result = chardet.detect(file.read())
    encoding = result['encoding'] # 'utf-8'

In [2]:
# 데이터프레임 출력 옵션 
# row 생략 없이 출력
# pd.set_option('display.max_rows', None)
# col 생략 없이 출력
pd.set_option('display.max_columns', None)

In [41]:
df = pd.read_csv('modeldata_df_NAdropped.csv', encoding=encoding)

In [42]:
df

Unnamed: 0          tm  ta_max_t-0  ta_min_t-0  ta_max_min_t-0  \
0                0  2018-01-03        -0.4        -7.1             6.7   
1                1  2018-01-04        -0.7        -8.7             8.0   
2                2  2018-01-04        -0.7        -8.7             8.0   
3                3  2018-01-05         1.6        -5.6             7.2   
4                4  2018-01-05         1.6        -5.6             7.2   
...            ...         ...         ...         ...             ...   
544395      597663  2023-12-27         6.6        -3.0             9.6   
544396      597664  2023-12-28         7.4        -3.8            11.2   
544397      597665  2023-12-29         9.3         1.6             7.7   
544398      597666  2023-12-30         6.0         1.4             4.6   
544399      597667  2023-12-31         3.0         0.6             2.4   

        rn_day_t-0  ws_max_t-0  ws_ins_max_t-0  ws_mean_t-0  ws_min_t-0  \
0              0.0         3.5             6.6          2.1         0.8   
1              0.0         3.5             5.8          1.4         0.5   
2              0.0         3.5             5.8          1.4         0.5   
3              0.0         3.6             8.0          1.7         0.6   
4              0.0         3.6             8.0          1.7         0.6   
...            ...         ...             ...          ...         ...   
544395         0.0         4.1             5.5          2.2         0.7   
544396         0.0         6.5            10.1          3.0         0.2   
544397         0.0         7.2            10.2          4.1         1.9   
544398         0.5         5.8             9.0          1.9         0.3   
544399        11.0         5.2             7.9          2.0         0.2   

        hm_max_t-0  hm_mean_t-0  hm_min_t-0  ta_max_t-1  ta_min_t-1  \
0             54.0         41.1        29.3         1.8        -4.3   
1             56.7         44.1        31.3        -0.4        -7.1   
2             56.7         44.1        31.3        -0.4        -7.1   
3             56.0         48.5        33.5        -0.7        -8.7   
4             56.0         48.5        33.5        -0.7        -8.7   
...            ...          ...         ...         ...         ...   
544395        83.6         61.7        48.1         6.5         0.1   
544396        89.0         54.1        24.5         6.6        -3.0   
544397        54.5         44.2        29.8         7.4        -3.8   
544398        94.4         68.9        46.0         9.3         1.6   
544399        95.9         91.9        85.6         6.0         1.4   

        ta_max_min_t-1  rn_day_t-1  ws_max_t-1  ws_ins_max_t-1  ws_mean_t-1  \
0                  6.1         0.0         4.9             8.5          1.8   
1                  6.7         0.0         3.5             6.6          2.1   
2                  6.7         0.0         3.5             6.6          2.1   
3                  8.0         0.0         3.5             5.8          1.4   
4                  8.0         0.0         3.5             5.8          1.4   
...                ...         ...         ...             ...          ...   
544395             6.4         0.0        10.5            15.5          5.9   
544396             9.6         0.0         4.1             5.5          2.2   
544397            11.2         0.0         6.5            10.1          3.0   
544398             7.7         0.0         7.2            10.2          4.1   
544399             4.6         0.5         5.8             9.0          1.9   

        ws_min_t-1  hm_max_t-1  hm_mean_t-1  hm_min_t-1  ta_max_t-2  \
0              0.2        70.6         43.6        20.1         3.8   
1              0.8        54.0         41.1        29.3         1.8   
2              0.8        54.0         41.1        29.3         1.8   
3              0.5        56.7         44.1        31.3        -0.4   
4              0.5        56.7         44.1        31.3      

# 의사결정트리
- 알고리즘
    - C4.5: 엔트로피 계수를 가장 많이 감소시키는 변수를 찾아 분리
    - CART (Classification And Regression Tree): 범주형 목표변수인 경우 지니지수를 가장 많이 감소시키는 변수로 분리
    - CHAID (Chi-Squeared Automatic Interaction Detection): p-value가 가장 작은 변수를 찾아 분리
 
- recall, precision 파라미터
    - macro: 각 클래스에 동일한 중요도 부여, 클래스 불균형 무시
    - micro: 전체 클래스의 총 합계를 사용하여 계산, 클래스의 불균형 반영
    - weighted: 각 클래스의 샘플 수를 가중치로 사용하여 계산, 클래스의 불균형 반영 

In [44]:
# nan 값 전처리 - y 값
df['type'] = df['type'].fillna('없음')
df['ignition'] = df['ignition'].fillna('없음')
df['location'] = df['location'].fillna('없음')
df['grade'] = df['grade'].fillna('없음')

df['casualties'] = df['casualties'].fillna(-1)
df['property_damage'] = df['property_damage'].fillna(-1)

In [29]:
# drop na - x 값 
df = df.dropna()

In [46]:
df.isna().sum()

Unnamed: 0         0
tm                 0
ta_max_t-0         0
ta_min_t-0         0
ta_max_min_t-0     0
rn_day_t-0         0
ws_max_t-0         0
ws_ins_max_t-0     0
ws_mean_t-0        0
ws_min_t-0         0
hm_max_t-0         0
hm_mean_t-0        0
hm_min_t-0         0
ta_max_t-1         0
ta_min_t-1         0
ta_max_min_t-1     0
rn_day_t-1         0
ws_max_t-1         0
ws_ins_max_t-1     0
ws_mean_t-1        0
ws_min_t-1         0
hm_max_t-1         0
hm_mean_t-1        0
hm_min_t-1         0
ta_max_t-2         0
ta_min_t-2         0
ta_max_min_t-2     0
rn_day_t-2         0
ws_max_t-2         0
ws_ins_max_t-2     0
ws_mean_t-2        0
ws_min_t-2         0
hm_max_t-2         0
hm_mean_t-2        0
hm_min_t-2         0
type               0
ignition           0
location           0
grade              0
casualties         0
property_damage    0
isFire             0
district_1         0
district_2         0
dtype: int64

## x: 기상데이터

### 1) 화재 type ~ 기상데이터

In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix
import warnings 
warnings.filterwarnings('ignore')

# x값, y값 분리
x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# DecisionTree Classifier 생성 
model = DecisionTreeClassifier(random_state=42)

# StratifiedKFold 
skfold = StratifiedKFold(n_splits=3)
k=0 # 교차검증 횟수
cv_acc = [] # 교차검증마다 정확도 저장 

for train_idx, test_idx in skfold.split(x, y):
    k += 1
    print(f'{k}번째 검증 데이터 셋')

    x_train, x_test = x.iloc[train_idx], x.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(x_train, y_train)
    y_hat = model.predict(x_test)
    # 평가지표 
    accuracy = accuracy_score(y_test, y_hat)
    precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
    recall = recall_score(y_test, y_hat, average='macro')
    cm = confusion_matrix(y_test, y_hat)
    
    print(f'정확도: {acc:.2f}')
    print(f'정밀도: {precision:.2f}')
    print(f'재현율: {recall:.2f}')
    print(cm)
    print()
    cv_acc.append(acc)

print()
print(f'평균 정확도: {np.mean(cv_acc):.2f}')

1번째 검증 데이터 셋
정확도: 0.49
정밀도: 0.14
재현율: 0.14
[[65746 35147  6010   110    19  1274  3540]
 [26070 13681  2721    56    10   625  1513]
 [ 6912  4604   836    12     4   230   347]
 [  132    78    13     0     0     3     7]
 [   27    22     6     0     0     0     1]
 [ 1237  1544   329     1     2    49   145]
 [ 4317  3272   475     9     3   101   227]]

2번째 검증 데이터 셋
정확도: 0.49
정밀도: 0.13
재현율: 0.13
[[73348 27269  5162    97    31  1979  3960]
 [30569  7640  2372    43    10  2010  2032]
 [ 7195  3895   672    10     7   674   492]
 [  118    78    22     0     2     2    11]
 [   33    13     6     0     0     4     1]
 [ 1589  1183   268     3     4   113   146]
 [ 5067  2298   409    10     0   359   261]]

3번째 검증 데이터 셋
정확도: 0.49
정밀도: 0.14
재현율: 0.15
[[78908 20701  6143   227    31  2477  3358]
 [29856  7905  3661   165     8  1542  1539]
 [ 8606  2572   864    33     5   517   349]
 [  167    40    10     1     0     7     8]
 [   35    11     3     3     0     2     2]
 [ 2075   74

### parameter tuning

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_type1 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_2, param_grid=param_grid, cv=cv, scoring='accuracy', n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

x = df[['ta_max_t-0', 'ta_min_t-0', 'ta_max_min_t-0', 'rn_day_t-0',
       'ws_max_t-0', 'ws_ins_max_t-0', 'ws_mean_t-0', 'ws_min_t-0',
       'hm_max_t-0', 'hm_mean_t-0', 'hm_min_t-0', 'ta_max_t-1', 'ta_min_t-1',
       'ta_max_min_t-1', 'rn_day_t-1', 'ws_max_t-1', 'ws_ins_max_t-1',
       'ws_mean_t-1', 'ws_min_t-1', 'hm_max_t-1', 'hm_mean_t-1', 'hm_min_t-1',
       'ta_max_t-2', 'ta_min_t-2', 'ta_max_min_t-2', 'rn_day_t-2',
       'ws_max_t-2', 'ws_ins_max_t-2', 'ws_mean_t-2', 'ws_min_t-2',
       'hm_max_t-2', 'hm_mean_t-2', 'hm_min_t-2']]
y = df['type']

# 훈련 데이터와 테스트 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42, stratify=y)

# 의사결정 나무 모델 생성
tree_type2 = DecisionTreeClassifier(random_state=42)

# 파라미터 그리드 설정
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 3, 5, 10],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [10, 20, 30]
}

# GridSearchCV 설정
cv = StratifiedKFold(n_splits=3)
grid_search = GridSearchCV(estimator=tree_2, param_grid=param_grid, cv=cv, scoring='accuracy', n_jobs=-1)

# 모델 훈련
grid_search.fit(x_train, y_train)

# 최적의 파라미터 출력
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation accuracy: {:.2f}".format(grid_search.best_score_))

# 테스트 데이터에 대한 예측
y_hat = grid_search.predict(x_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_hat)
precision = precision_score(y_test, y_hat, average='macro') # macro, micro, weighted 중 선택
recall = recall_score(y_test, y_hat, average='macro')
cm = confusion_matrix(y_test, y_hat)

print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
print(cm)
print()

print("Classification Report:")
print(classification_report(y_test, y_hat))

### 2) ignition ~ 기상데이터

### 3) location ~ 기상데이터

### 4) grade ~ 기상데이터

#### 5) isFire ~ 기상데이터

## x: 기상 + 지역데이터